

-- COMANDO PARA CRIACAO DE BD
CREATE DATABASE AULA;

USE AULA;

-- COMANDO PARA CRIACAO DE TABELA
CREATE TABLE CURSO (
COD_CURSO INT NOT NULL PRIMARY KEY,
NOME VARCHAR (50) NOT NULL,
CARGA_HORARIA INT);

CREATE TABLE ALUNO (
RA INT NOT NULL PRIMARY KEY, 
NOME VARCHAR (100) NOT NULL,
TELEFONE CHAR (12),
CPF CHAR (11) NOT NULL);

-- COMANDO PARA ALTERAR A ESTRUTURA DA TABELA ALUNO E INCLUIR UMA COLUNA
ALTER TABLE ALUNO
ADD column COD_CURSO INT NOT NULL;

-- COMANDO PARA INCLUIR UMA CHAVE ESTRANGEIRA NA TABELA ALUNO
ALTER TABLE ALUNO
ADD CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO);

-- OUTRA FORMA DE CRIAR A TABELE
CREATE TABLE ALUNO (
RA INT NOT NULL PRIMARY KEY, 
NOME VARCHAR (100) NOT NULL,
TELEFONE CHAR (12),
CPF CHAR (11) NOT NULL,
COD_CURSO INT NOT NULL,
CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO));
