CREATE DATABASE ZOOLÓGICO;


CREATE TABLE ANIMAIS (
ID INT (4) PRIMARY KEY NOT NULL,
RAÇA VARCHAR(30) NOT NULL ,
NOME VARCHAR (30),
IDADE INT (2)
);

CREATE TABLE VETERINÁRIO (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR (30) NOT NULL,
ANIMAL int NOT NULL
);

ALTER TABLE VETERINÁRIO
ADD COLUMN ANIMAL VARCHAR(30) ;

INSERT INTO ANIMAIS 
(ID,RAÇA,NOME,IDADE)
VALUES (321,"LEÃO","ZÉZINHO",7);
INSERT INTO ANIMAIS 
VALUES (620,"MACACO","CHICO",15);
INSERT INTO ANIMAIS 
VALUES (705,"ELEFANTE","LIRO",11);
INSERT INTO ANIMAIS 
VALUES (407,"PINGUIN","PENINHA",5);

INSERT INTO VETERINÁRIO
(ID,NOME,ANIMAL)
VALUES (37,"JOSÉ","PINGUIN"), 
(81,"BRENO","MACACO"),
(62,"ALICE","LEÃO"),
(25,"ENRICO","ELEFANTE");


SELECT NOME,ID FROM VETERINÁRIO;
SELECT NOME,ID FROM ANIMAIS;
SELECT NOME,ID,ANIMAL FROM VETERINÁRIO
WHERE NOME = "ENRICO";